### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jrb80** [unlobito/ha-hildebrandglow#22]
I note this [integration no longer works](https://github.com/unlobito/ha-hildebrandglow/issues/19) and even previous hack fixes do not get it working. Is this project dead?

It would be a shame as it seemed like a cool integration for Home Assistant.

**Comment by unlobito** [comment]
Hey, apologies for the quiet over the last few months. It's been a weird time.

I think the best route forward will be completing #16 and moving the integration off HTTP polling.

I was struggling with the draft PR a lot in August since I wasn't able to find documentation around building integrations that directly tell HomeAssistant to connect to an MQTT server. I've tried looking for other integrations that I know use MQTT, but they seem to rely on external libraries (e.g. the [Roomba](https://github.com/home-assistant/core/tree/dev/homeassistant/components/roomba) component relies on [roombapy](https://github.com/pschmitt/roombapy) via [AMQTT](https://github.com/Yakifo/amqtt)).

Once MQTT connecting is resolved, I'd expect migrating the HTTP polling sensors to MQTT would be straightforward (especially given the documentation for the MQTT format available throughout the [Glowmarkt Forums](https://forum.glowmarkt.com/)).

I really appreciate your (& everyone else on #19's) interest in this integration. I'm hopeful that others might have ideas on how to move forward with this.

**Comment by worz9** [comment]
I tried also to get this going without success.  It would be really nice to get the real time readings/data into HA.  
Are there any folks with it still working ?

**Comment by arundalep** [comment]
I have but I used node red and MQTT, it works very well.

Sent from my iPhone

On 26 Mar 2021, at 11:48, worz9 ***@***.***> wrote:

﻿

I tried also to get this going without success. It would be really nice to get the real time readings/data into HA.
Are there any folks with it still working ?

**Comment by worz9** [comment]
> Hey, apologies for the quiet over the last few months. It's been a weird time.
> 
> I think the best route forward will be completing #16 and moving the integration off HTTP polling.
> 
> I was struggling with the draft PR a lot in August since I wasn't able to find documentation around building integrations that directly tell HomeAssistant to connect to an MQTT server. I've tried looking for other integrations that I know use MQTT, but they seem to rely on external libraries (e.g. the [Roomba](https://github.com/home-assistant/core/tree/dev/homeassistant/components/roomba) component relies on [roombapy](https://github.com/pschmitt/roombapy) via [AMQTT](https://github.com/Yakifo/amqtt)).
> 
> Once MQTT connecting is resolved, I'd expect migrating the HTTP polling sensors to MQTT would be straightforward (especially given the documentation for the MQTT format available throughout the [Glowmarkt Forums](https://forum.glowmarkt.com/)).
> 
> I really appreciate your (& everyone else on #19's) interest in this integration. I'm hopeful that others might have ideas on how to move forward with this.

Harley - are you saying the integration "as is" does not work anymore?  Knowing this would be great so I can go down other routes - perhaps MQTT or NodeRed  Thx. Andrew

**Comment by unlobito** [comment]
@worz9- I was able to freshly setup the integration using the `master` branch. If you're able to directly use MQTT (either directly or through NodeRED), I'd suggest doing that at this time since it'd be significantly less resource intensive for the folks at Hildebrand than the polling approach currently used by this integration.

I'd be interested in updating this integration in the future to directly use [AMQTT](https://github.com/Yakifo/amqtt) so folk don't have to manually map the different Zigbee entities to human-readable names.

**Comment by worz9** [comment]
Harley,

Thanks - I have focused on MQTT now

Have it configured pending Jane@Glow turning it on !
I have lots of NodeRed flows so this works for me, but will try templates too :-)

I did try it once more using the master branch, but no success again.

Andrew
