### ISSUE TITLE
Is this actually maintained at all? Doesn't ever appear on Integrations after adding from HACS.

### ISSUE THREAD

**Issue by user897943** [unlobito/ha-hildebrandglow#38]
I installed this for the first time on HA 2021.7.0, then 2021.8.0, now 2021.9.0 and the subsequent incremental updates for each monthly release, I installed from HACS, it does not display any errors, so for three months I try to add this from the Integrations page on HA and there's no "Hildebrand" entry, no "Glow" entry, or anything of the sort. It's simply not there even though it's installed on HACS. I even got an update a few minutes ago on HACS, restarted, and.... nothing. Not available in Integrations.

What's up with this? Is this even being supported and tested? I am always grateful for the time people dedicate to sharing things with others but if they're gonna share, please make sure it works, nobody wants to have their time wasted.

**Comment by danstreeter** [comment]
I _believe_ that this is due to the recent updates of HA requiring a version number in manifest files, which the mainstream branch of this repo (the one published to HACS) does not include.

It has however been fixed on beta branches which utilise MQTT for data exposure - please see this comment (and thread) for more info.

_Note: I'm not a maintainer of this repo, just a user who fell into the same issues but now has it running ok._

**Comment by unlobito** [comment]
<img width="425" alt="imagen" src="https://user-images.githubusercontent.com/5637/132959356-e83d8ba3-7453-4658-880f-a874ced34227.png">

HACS should default to the `mqtt` branch since this repo's default branch was changed a few days ago (https://github.com/unlobito/ha-hildebrandglow/pull/36#issuecomment-915195357)

<img width="532" alt="imagen" src="https://user-images.githubusercontent.com/5637/132959378-0588b904-197a-4051-bb34-188810110079.png">

If you have Hildebrand's CAD hardware, you should then be able to add the integration through the settings UI.

Feel free to reopen this issue if you're still having trouble getting the integration set up.
